### ISSUE TITLE
MarketSnapShot OSErr 22

### ISSUE THREAD

**Issue by jboxsc163** [FutunnOpen/OpenQuant#57]
在 sample.py 改了一點做測試, 出現奇 OSErr 22
使用 window 7 英文, python 3.6.1

def _example_get_market_snapshot(quote_ctx):
    stk = ["HK.00700","HK.00001","HK.00002","HK.00003","HK.00005"]
    ret_status, ret_data = quote_ctx.get_market_snapshot(stk)

    #ret_status, ret_data = quote_ctx.get_market_snapshot(["US.AAPL", HK.00700"])

    if ret_status == RET_ERROR:
        print(ret_data)
        exit()
    print("market_snapshot")
    print(ret_data)

Output
Traceback (most recent call last):
  File "sample.py", line 322, in <module>
    _example_get_market_snapshot(quote_context)
  File "sample.py", line 154, in _example_get_market_snapshot
    ret_status, ret_data = quote_ctx.get_market_snapshot(stk)
  File "D:\temp\ftsnap\openft\open_quant_context.py", line 753, in get_market_sn
apshot
    ret_code, msg, snapshot_list = query_processor(**kargs)
  File "D:\temp\ftsnap\openft\open_quant_context.py", line 489, in sync_query_pr
ocessor
    ret_code, msg, content = unpack_func(rsp_str)
  File "D:\temp\ftsnap\openft\quote_query.py", line 485, in unpack_rsp
    } for record in raw_snapshot_list]
  File "D:\temp\ftsnap\openft\quote_query.py", line 485, in <listcomp>
    } for record in raw_snapshot_list]
OSError: [Errno 22] Invalid argument

**Comment by FutunnOpen** [comment]
更新api版本(master分支)
